AWSTemplateFormatVersion: 2010-09-09
Description: |
  Simple but complete website distribution stack 
  Prerequisites: a Route53 domain plus its Hosted Zone ID
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label: 
        default: DNS
      Parameters:
        - Domain
        - HostedZoneID
    - Label: 
        default: Distribution Config
      Parameters:
        - DefaultRootObject
        - DefaultTTL
        - MaxTTL
        - MinTTL
Parameters:
  Domain:
    Description: The domain of your website
    Type: String
  HostedZoneID:
    Description: The ID of your hosted zone in Route 53
    Type: AWS::Route53::HostedZone::Id
  DefaultTTL:
    Type: Number
    Default: 3600 # 1h
    Description: Default cache object TTL
  MaxTTL:
    Type: Number
    Default: 7200 # 2h
    Description: Maximum cache object TTL
  MinTTL:
    Type: Number
    Default: 1800 # 1/2h
    Description: Minimum cache object TTL
  DefaultRootObject:
    Type: String
    Default: index.html
    Description: Default root object path used by the CloudFront distribution
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CFS3OAI # required 4 some reason
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowOriginAccessIdentity
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - !Sub arn:aws:s3:::${WebsiteBucket}
              - !Sub arn:aws:s3:::${WebsiteBucket}/*
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: !Ref DefaultTTL
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: !Ref MaxTTL
          MinTTL: !Ref MinTTL
          TargetOriginId: WebsiteBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: !Ref DefaultRootObject
        Enabled: true
        # routing ipv6 traffic from Route53 to CloudFront would require an AAAA 
        # alias record which carries along extra cost
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: WebsiteBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificate
          MinimumProtocolVersion: TLSv1.2_2018
          SSLSupportMethod: sni-only
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: !Ref Domain
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # This Zone ID is used for any CloudFront Distribution
        DNSName: !GetAtt WebsiteDistribution.DomainName
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      ValidationMethod: DNS
Outputs:
  AcmCertificateArn: 
    Value: !Ref ACMCertificate
  WebsiteBucketName:
    Description: S3 Bucket Name
    Value: !Ref WebsiteBucket
  DistributionDomainName:
    Value: !GetAtt WebsiteDistribution.DomainName
  URL:
    Description: URL of your website
    Value: !If
      - ShouldCreateCert
      - !Sub https://${Domain}
      - !Sub http://${Domain}