AWSTemplateFormatVersion: 2010-09-09
Description: Website distribution stack with a private S3 bucket
Parameters:
  DefaultTTL:
    Type: Number
    Default: 3600 # 1h
    Description: Default cache object TTL
  MaxTTL:
    Type: Number
    Default: 7200 # 2h
    Description: Maximum cache object TTL
  MinTTL:
    Type: Number
    Default: 1800 # 1/2h
    Description: Minimum cache object TTL
  DefaultRootObject:
    Type: String
    Default: index.html
    Description: Default root object name used by the CloudFront distribution
  TargetOriginId:
    Type: String
    Default: WebsiteBucketOrigin
    Description: Id for the target S3 origin of the CloudFront distribution
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CFS3OAI # required 4 some reason
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowOriginAccessIdentity
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - !Sub arn:aws:s3:::${WebsiteBucket}
              - !Sub arn:aws:s3:::${WebsiteBucket}/*
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: !Ref DefaultTTL
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: !Ref MaxTTL
          MinTTL: !Ref MinTTL
          TargetOriginId: !Ref TargetOriginId
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: !Ref DefaultRootObject
        Enabled: true
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: !Ref TargetOriginId
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        PriceClass: PriceClass_100
        # ViewerCertificate:
        #   AcmCertificateArn: ... # arn of our acm certificate
        #   MinimumProtocolVersion: TLSv1.2_2018
        #   SSLSupportMethod: sni-only
Outputs:
  DistributionURL:
    Value: !GetAtt WebsiteDistribution.DomainName