AWSTemplateFormatVersion: 2010-09-09
Description: website distribution
# Conditions:
#   inAllowedRegion: !Equals
#     - !Ref AWS::Region
#     - eu-west-3 # paris
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CFS3OAI # required 4 some reason
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCFS3OAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - !Sub arn:aws:s3:::${WebsiteBucket}
              - !Sub arn:aws:s3:::${WebsiteBucket}/*
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # 1h
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 7200 # 2h
          MinTTL: 1800 # 1/2h
          TargetOriginId: WebsiteBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: WebsiteBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        PriceClass: PriceClass_100
        # ViewerCertificate:
        #   AcmCertificateArn: ... # arn of our acm certificate
        #   MinimumProtocolVersion: TLSv1.2_2018
        #   SSLSupportMethod: sni-only
Outputs:
  DistributionURL:
    Value: !GetAtt WebsiteDistribution.DomainName