# updates an aws cloudformation stack when either index.html, stack.yml, or 
# this file itself is changed in the test branch. this template assumes that the
# corresponding stack has initially been created through a manual action as the
# deployment steps only performs updates. Moreover, this template relies on two
# secrets: AWS_ACCESS_KEY_ID_TEST, AWS_SECRET_ACCESS_KEY_TEST. These must be the
# security credentials of the iam user included in the stack. Get the 
# credentials from the iam console. Lastly, this template assumes that the 
# stack is called NuggetWebStack - see env.
name: continous deployment
on:
  push:
    branches:
      - test
    paths:
      - index.html
      - stack.yml
      - .github/workflows/cd.yml
env:
  STACK_NAME: NuggetWebStack
  BUCKET_NAME: ""
jobs:
  deploy:
    name: test environment deployment
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v1.0.0
      - name: authenticate with aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: eu-west-3
      - name: validate the cloudformation template
        run: aws cloudformation validate-template --template-body="$(cat ./stack.yml)"
      - name: update the web stack
        run: aws cloudformation update-stack --stack-name=${{ env.STACK_NAME }} --template-body="$(cat ./stack.yml)" --capabilities=CAPABILITY_IAM
      - name: determine the web stack's bucket name
        run: |
          _BUCKET_NAME="$(aws cloudformation describe-stack-resources --stack-name=${{ env.STACK_NAME }} | jq '.StackResources[] | select(.ResourceType == "AWS::S3::Bucket") | .PhysicalResourceId')"
          echo "::set-env name=BUCKET_NAME::$_BUCKET_NAME"
      - name: update the website content
        run: aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}