name: cd
on:
  push:
    branches:
      - test
      - master
    paths:
      - index.html
      - stack.yml
      - "**/cd.yml"
env:
  BRANCH: tr a-z A-Z <<< ${GITHUB_REF##*/}
  # _AWS_ACCESS_KEY_ID: ${{ format('AWS_ACCESS_KEY_ID_{0}', env.BRANCH) }}
  # _AWS_SECRET_ACCESS_KEY: ${{ format('AWS_SECRET_ACCESS_KEY_{0}', env.BRANCH) }}
  # _AWS_CLOUDFORMATION_STACK_NAME: ${{ format('AWS_CLOUDFORMATION_STACK_NAME_{0}', env.BRANCH) }}
  # _AWS_S3_BUCKET_NAME: ${{ format('AWS_S3_BUCKET_NAME_{0}', env.BRANCH) }}
jobs:
  test:
    name: deploy $BRANCH environment to aws
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v1.0.0
      # aws-cli comes bundled in github actions
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', env.BRANCH)] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', env.BRANCH)] }}
          aws-region: eu-west-3
      - name: validate the cloudformation template
        run: |
          aws cloudformation validate-template \
            --template-body="$(cat ./stack.yml)"
      - name: update the cloudformation stack
        run: |
          aws cloudformation update-stack \
            --stack-name=${{ secrets[format('AWS_CLOUDFORMATION_STACK_NAME_{0}', env.BRANCH)] }} \
            --template-body="$(cat ./stack.yml)"
      - name: update s3 bucket with index.html
        run: aws s3 copy ./index.html s3://${{ secrets[format('AWS_S3_BUCKET_NAME_{0}', env.BRANCH)] }}