name: cd
on:
  push:
    branches:
      - test
      - master
    paths:
      - index.html
      - stack.yml
      - .github/workflows/cd.yml
jobs:
  test:
    name: deploy ${{ github.ref }} environment to aws
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v1.0.0
      # aws-cli comes bundled in github actions
      - name: configure aws credentials for the test environment
        if: endsWith(github.ref, "test")
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: eu-west-3
      - name: configure aws credentials for the master environment
        if: endsWith(github.ref, "master")
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MASTER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MASTER }}
          aws-region: eu-west-3
      - name: validate the cloudformation template
        run: |
          aws cloudformation validate-template \
            --template-body="$(cat ./stack.yml)"
      - name: update the cloudformation stack in the test environment
        if: endsWith(github.ref, "test")
        run: |
          aws cloudformation update-stack \
            --stack-name=${{ secrets.AWS_CLOUDFORMATION_STACK_NAME_TEST }} \
            --template-body="$(cat ./stack.yml)"
      - name: update the cloudformation stack in the master environment
        if: endsWith(github.ref, "master")
        run: |
          aws cloudformation update-stack \
            --stack-name=${{ secrets.AWS_CLOUDFORMATION_STACK_NAME_MASTER }} \
            --template-body="$(cat ./stack.yml)"
      - name: update the website content in the test environment
        if: endsWith(github.ref, "test")
        run: aws s3 copy ./index.html s3://${{ secrets.AWS_S3_BUCKET_NAME_TEST] }}
      - name: update the website content in the master environment
        if: endsWith(github.ref, "master")
        run: aws s3 copy ./index.html s3://${{ secrets.AWS_S3_BUCKET_NAME_MASTER] }}